# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:00
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name': '文章详细表', 'verbose_name_plural': '文章详细表'},
        ),
        migrations.AlterModelOptions(
            name='articleup',
            options={'verbose_name': '文章点赞表', 'verbose_name_plural': '文章点赞表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '站点信息', 'verbose_name_plural': '站点信息'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '博主个人文章分类表', 'verbose_name_plural': '博主个人文章分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='commentup',
            options={'verbose_name': '评论点赞表', 'verbose_name_plural': '评论点赞表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签名称表', 'verbose_name_plural': '标签名称表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
