# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171121_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArticlecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='sitearticlecategory',
            name='siteCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.SiteCategory'),
        ),
    ]
