# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171121_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitearticlecategory',
            options={'verbose_name': '文章类型表', 'verbose_name_plural': '文章类型表'},
        ),
        migrations.AlterModelOptions(
            name='sitecategory',
            options={'verbose_name': '类型表', 'verbose_name_plural': '类型表'},
        ),
    ]
