# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171121_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type_id',
        ),
        migrations.AddField(
            model_name='article',
            name='SiteArticlecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SiteArticlecategory'),
        ),
    ]
