# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171122_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('up_count', 'down_count')]),
        ),
        migrations.AlterUniqueTogether(
            name='articleup',
            unique_together=set([('article', 'user')]),
        ),
    ]
