# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171124_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
    ]
